import { expect, test } from '@playwright/test'

test('playable smoke path reaches the restoration atlas systems', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'EchoGraft' })).toBeVisible()
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  await expect(page.getByRole('heading', { name: /Training Contract: First Breath/ })).toBeVisible()
  await expect(page.locator('.a-game--status')).toHaveCount(0)
  await expect(page.locator('.a-game--inventory')).toHaveCount(0)

  const eventLog = page.getByLabel('Caption and event log')
  await page.getByRole('button', { name: 'Listen' }).click()
  await expect(eventLog.getByText(/Listen: Training Contract: First Breath/)).toBeVisible()
  await page.getByRole('button', { name: 'Locate heart' }).click()
  await expect(eventLog.getByText(/Locate: chamber heart is/)).toBeVisible()
  await expect(eventLog.getByText(/Locate: chamber heart is .* Heart scan: direction .* distance .* objective/)).toBeVisible()
  await page.getByRole('button', { name: 'Tune up' }).click()
  await expect(eventLog.getByText(/Tuned Sol phonoseed: pitchRatio is 1.05/)).toBeVisible()
  await page.getByRole('button', { name: 'Tune down' }).click()
  await expect(eventLog.getByText(/Tuned Sol phonoseed: pitchRatio is 1 .* Single-seed tuning role/)).toBeVisible()
  await page.getByRole('button', { name: 'Restore chamber' }).click()
  await expect(eventLog.getByText(/Restore: Training Contract: First Breath is not ready/)).toBeVisible()
  await page.getByRole('button', { name: 'Evaluate resonance' }).click()
  await expect(eventLog.getByText(/Evaluate resonance: Resonance accuracy 0 percent \(weak\).*Plant 1 more seed/)).toBeVisible()
  await page.keyboard.press('o')
  await expect(eventLog.getByText(/Objective: .* Current system: Intake\./)).toBeVisible()
  await page.keyboard.press('p')
  await expect(eventLog.getByText(/Position: .* facing .* Progress: 0 of \d+ contracts restored; 0 of \d+ Ark systems online/)).toBeVisible()
  await page.keyboard.press('i')
  await expect(eventLog.getByText(/Inventory:/)).toBeVisible()
  await page.keyboard.press('l')
  await expect(eventLog.getByText(/Latest log: Inventory:/)).toBeVisible()
  await page.keyboard.press('Shift+L')
  await expect(eventLog.getByText(/Recent log: .*Latest log:/)).toBeVisible()
  await page.keyboard.press('x')
  await expect(eventLog.getByText(/Boundaries: west .* Return point/)).toBeVisible()
  await expect(eventLog.getByText(/Boundary scan: chamber edges .* Exits: safe return point .* Safe return point/)).toBeVisible()
  await page.keyboard.press('v')
  await expect(eventLog.getByText(/Planted voices: none in this chamber/)).toBeVisible()
  await page.keyboard.press('c')
  await expect(eventLog.getByText(/Codex: no records recovered yet/)).toBeVisible()

  await page.keyboard.press('Space')
  await expect(eventLog.getByText(/Objective scan: heart/)).toBeVisible()
  await expect(eventLog.getByText(/Objective scan: heart .* Heart scan: direction .* distance .* objective/)).toBeVisible()
  await expect(eventLog.getByText(/shape .* Target traits: .* Hazards: .* Required changes:/)).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('Space')
  await expect(eventLog.getByText(/^Boundary scan: chamber edges .* Exits: safe return point .* Safe return point/)).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('Space')
  await expect(eventLog.getByText(/Seed scan: no planted seed objects/)).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('Space')
  await expect(eventLog.getByText('Hazard scan: no forbidden intervals or unsafe zones detected in this chamber.', { exact: true })).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('Space')
  await expect(eventLog.getByText(/Memory scan: records none recovered yet.*Chamber records: First Breath hidden/)).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('Space')
  await expect(eventLog.getByText(/Network scan: endgame multi-chamber resonance building; 0 online system/)).toBeVisible()

  await page.keyboard.press('ArrowUp')
  await expect(eventLog.getByText(/Movement audio: spatial footstep, wall .* current .* landmark heart/)).toBeVisible()
  await expect(eventLog.getByText(/No-sight movement cues: spatial footstep, directional placement, wall distance, exit presence, current status, heart landmark, surface timbre/)).toBeVisible()
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await expect(eventLog.getByText(/Meaningful position: within .* chamber heart/)).toBeVisible()
  await page.keyboard.press('v')
  await expect(eventLog.getByText(/Planted voices: Sol phonoseed at/)).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('z')
  await page.keyboard.press('z')
  await page.keyboard.press('Space')
  await expect(eventLog.getByText(/Seed scan: Sol phonoseed at .* Tuning state: pitch .* pulse .* brightness .* phase .* waveform/)).toBeVisible()
  await expect(eventLog.getByText(/solved with Resonant rating/)).toBeVisible()
  await expect(eventLog.getByText(/Intake system restored and online/)).toBeVisible()
  await expect(eventLog.getByText(/Seed moves used 1; efficient/)).toBeVisible()
  await expect(eventLog.getByText(/Graft stability not needed/)).toBeVisible()
  await expect(eventLog.getByText(/Hazard containment clear/)).toBeVisible()
  await expect(eventLog.getByText(/Resource efficiency conserved/)).toBeVisible()
  await expect(eventLog.getByText(/Optional record recovery recovered/)).toBeVisible()
  await page.getByRole('button', { name: 'Restore chamber' }).click()
  await expect(eventLog.getByText(/already restored with Resonant rating/)).toBeVisible()
  await expect(eventLog.getByText(/Codex updated: First Breath/)).toBeVisible()

  await page.getByRole('button', { name: 'Choose next contract' }).click()
  await expect(page.getByRole('heading', { name: 'Restoration Atlas' })).toBeVisible()
  await expect(page.getByText(/Season 1 contracts: 1 restored. Materials: biomass 1/)).toBeVisible()
  await expect(page.getByText(/Systems online: Intake/)).toBeVisible()
  await expect(page.getByText(/Environmental changes: Intake: Training Contract: First Breath stabilized with Resonant resonance/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Major Ark Systems' })).toBeVisible()
  await expect(page.getByText(/Heart: network resonance and endgame resolutions/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Stewardship Review' })).toBeVisible()
  await expect(page.getByText(/1 of 4\d contracts restored/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Navigation Atlas' })).toBeVisible()
  await expect(page.getByText(/Navigation atlas previews limited/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Water Root Routing' })).toBeVisible()
  await expect(page.getByText(/Water root routing locked/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Canopy Photosynthesis Doors' })).toBeVisible()
  await expect(page.getByText(/Canopy photosynthesis doors locked/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Memory Codex Echoes' })).toBeVisible()
  await expect(page.getByText(/Memory codex echoes locked/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Heart Network Endings' })).toBeVisible()
  await expect(page.getByText(/Heart network resonance locked/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Final Ecology Philosophy' })).toBeVisible()
  await expect(page.getByText(/Final ecology philosophy support aligned/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Decision Point' })).toBeVisible()
  await expect(page.getByText(/Recommended next work: Contract 1: Intake Lung/)).toBeVisible()
  await expect(page.getByText(/Post-restore options: improve the active chamber, take another work order, research grafts, or advance the Ark clock/)).toBeVisible()
  await page.getByRole('button', { name: 'Advance Ark clock' }).click()
  await expect(page.getByLabel('Caption and event log').getByText(/Ark clock advanced to cycle 1/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Accept work order' }).nth(1)).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Accept work order' }).nth(2)).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Enter active chamber' })).toBeVisible()

  await page.getByRole('button', { name: 'Seed library' }).click()
  await expect(page.getByText(/Selected seed DNA: Seed name: Sol phonoseed; catalog id sol/)).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Seed family: Sol; affinity oxygen and stable pitch; discovered origin Intake lung/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Ecological affinity: oxygen and stable pitch; restoration role for Sol ecology/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Discovered origin: Intake lung; origin record for Sol lineage and Memory codex echoes/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Pitch ratio: 1; target delta 0; root interval against the chamber heart/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Pulse rate: 1; target delta 0; rhythmic growth and system timing/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Brightness\/filter: 0.45; target delta 0; filter opening and canopy light color/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Phase: 0 degrees; target offset 0 degrees; alignment, cancellation, and hidden echo behavior/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Waveform: sine; timbre shape for synthesis and graft inheritance; matches any chamber-compatible waveform/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Synth type: (pure|fm|am|noise-kissed); routes to .* Syngen voice/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Modulation profile: FM .*pressure, root grit, and harmonic edge.*AM .*current sway and rhythmic amplitude motion.*noise .*breath, compost, and masking texture.*dominant layer/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Envelope: attack .*how quickly the seed voice blooms.*decay .*sustain .*release .*how long the seed voice lingers.*ADSR shape controls bloom, body, and lingering tail/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Noise profile: .*breath, compost, and masking texture.*routes through .* Syngen/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Growth behavior: .*pulse growth window, about .* seconds; no reflex timing required/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Seed Collection Appraisal' })).toBeVisible()
  await expect(page.getByText(/Exchange remains restoration support/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Seed Family Catalog' })).toBeVisible()
  await expect(page.getByText(/24 known families and 96 possible graft discoveries/)).toBeVisible()
  await page.getByRole('button', { name: 'Select Lumen phonoseed' }).click()
  await expect(page.getByText(/Selected Lumen phonoseed/)).toBeVisible()
  await page.getByRole('button', { name: 'FM modulation' }).click()
  await page.getByRole('button', { name: 'Tune up' }).click()
  await expect(page.getByText(/Tuned Lumen phonoseed: fmAmount is .* FM modulation/)).toBeVisible()
  await page.getByRole('button', { name: 'growth behavior' }).click()
  await page.getByRole('button', { name: 'Tune up' }).click()
  await expect(page.getByText(/Tuned Lumen phonoseed: growthBehavior is .* growth behavior/)).toBeVisible()
  await page.getByRole('button', { name: 'Graft first two seeds' }).click()
  await expect(page.getByText(/First graft: Sol phonoseed plus Lumen phonoseed created Sol-Lumen graft.*root pitch 1 from Sol phonoseed.*waveform sine from Sol phonoseed.*modulation FM .* AM .* noise .* from Lumen phonoseed.*growth .* from Lumen phonoseed/)).toBeVisible()
  await expect(page.getByText(/Grafted Sol-Lumen graft/)).toBeVisible()
  await expect(page.getByText(/Unlocked graft mechanic: hybrid resonance planting/)).toBeVisible()
  await expect(page.locator('li').filter({ hasText: /Sol-Lumen graft: .*Graft ancestry: Sol plus Lumen; archive record sol-lumen; hybrid traits inherited from parent seed lines/ })).toBeVisible()
  await page.getByRole('button', { name: 'Preview selected seed' }).click()
  await expect(page.getByText(/Previewing .* Audio preview: .* waveform .* synth .* growth/)).toBeVisible()
  await page.getByRole('button', { name: 'Atlas' }).click()

  await page.getByRole('button', { name: 'Codex' }).click()
  await expect(page.getByRole('heading', { name: 'First Breath' })).toBeVisible()
})

test('does not request external audio files', async ({ page }) => {
  const requests = []
  page.on('request', (request) => requests.push(request.url()))
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()
  expect(requests.filter((url) => /\.(mp3|wav|ogg|flac|m4a)(\?|$)/i.test(url))).toEqual([])
})

test('opens the postgame conservatory when unlocked', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('echograft-save-v1', JSON.stringify({
      version: 1,
      currentChamberId: 'finale',
      codexIds: ['first-breath'],
      endgameResolution: 'conservatory',
      materials: { biomass: 3, crystal: 2, memory: 2 },
      plantedByChamber: {},
      postgameUnlocked: true,
      ratings: { finale: 'Resonant' },
      solvedChambers: ['tutorial', 'finale'],
      inventoryIds: ['sol', 'lumen', 'umbra', 'spire'],
      customSeeds: [],
      settings: {},
    }))
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'Ending resolution' }).click()
  await expect(page.getByText(/Resolution: Conservatory/)).toBeVisible()
  await page.getByRole('button', { name: 'Main menu' }).click()
  await page.getByRole('button', { name: 'Conservatory' }).click()
  await expect(page.getByRole('heading', { name: 'Conservatory' })).toBeVisible()
  await expect(page.getByText(/Postgame restoration is open/)).toBeVisible()
  await expect(page.getByText(/Composition Palette/)).toBeVisible()
  await page.getByRole('button', { name: 'Compose conservatory chord' }).click()
  await expect(page.getByText(/Compose: playing 4 recovered seed voice/)).toBeVisible()
})
