import { expect, test } from '@playwright/test'

test('playable smoke path reaches the restoration atlas systems', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'EchoGraft' })).toBeVisible()
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await expect(page.getByRole('navigation', { name: 'Main menu' })).toBeVisible()
  await expect(page.getByText(/Current save: 0 of \d+ contracts restored; 0 of \d+ Ark systems online/)).toBeVisible()
  await page.getByRole('button', { name: 'New game' }).click()

  await expect(page.getByRole('heading', { name: /Training Contract: First Breath/ })).toBeVisible()
  await expect(page.locator('.a-game--status')).toHaveCount(0)
  await expect(page.locator('.a-game--inventory')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('heading', { name: 'Pause Functions' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Pause functions menu' })).toBeVisible()
  await expect(page.getByText(/Current save: 0 of \d+ contracts restored; 0 of \d+ Ark systems online/)).toBeVisible()
  await page.getByRole('button', { name: 'Settings' }).click()
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
  await expect(page.getByLabel('Settings controls')).toBeVisible()
  await expect(page.getByText(/Audio mix: master .* Reduced motion off; minimal visual mode off; high contrast off; scan verbosity detailed; text-only hints off/)).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Settings actions' })).toBeVisible()
  await expect(page.getByText(/Adjust master, ambience, music, UI, seed voice, hazard voice, and scan pulse levels independently/)).toBeVisible()
  await expect(page.getByLabel('Master volume')).toBeVisible()
  await expect(page.getByLabel('Ambience volume')).toBeVisible()
  await expect(page.getByLabel('Music volume')).toBeVisible()
  await expect(page.getByLabel('UI volume')).toBeVisible()
  await expect(page.getByLabel('Seed voice volume')).toBeVisible()
  await expect(page.getByLabel('Hazard voice volume')).toBeVisible()
  await expect(page.getByLabel('Scan pulse volume')).toBeVisible()
  await expect(page.getByLabel('Master volume')).toHaveValue('0.8')
  await expect(page.getByLabel('Ambience volume')).toHaveValue('0.55')
  await page.getByLabel('Master volume').focus()
  await page.keyboard.press('ArrowLeft')
  await expect(page.getByLabel('Caption and event log').getByText(/Settings audio\/display update: Master volume set to/)).toBeVisible()
  await expect(page.getByLabel('Ambience volume')).toHaveValue('0.55')
  await page.getByLabel('Reduced motion').check()
  await expect(page.locator('#app')).toHaveClass(/reduced-motion/)
  await expect(page.getByText(/Reduced motion removes screen transitions and animations while preserving all audio cues and caption-log feedback/)).toBeVisible()
  await expect(page.locator('.screen').first()).toHaveCSS('transition-duration', '0s')
  await expect(page.getByLabel('Caption and event log').getByText(/Settings audio\/display update: Reduced motion set to on/)).toBeVisible()
  await page.getByLabel('Minimal visual mode').check()
  await expect(page.locator('#app')).toHaveClass(/minimal-visual/)
  await expect(page.getByText(/Minimal visual mode hides the abstract radar and keeps the chamber playable through text, controls, and audio feedback/)).toBeVisible()
  await expect(page.getByLabel('Caption and event log').getByText(/Settings audio\/display update: Minimal visual mode set to on/)).toBeVisible()
  await page.getByLabel('High contrast').check()
  await expect(page.locator('#app')).toHaveClass(/high-contrast/)
  await expect(page.getByText(/High contrast increases border, focus, radar, and feedback contrast/)).toBeVisible()
  await expect(page.getByLabel('Scan verbosity')).toHaveValue('detailed')
  await expect(page.getByRole('button', { name: 'Back to game' })).toHaveCSS('border-top-color', 'rgb(255, 255, 255)')
  await expect(page.getByLabel('Caption and event log').getByText(/Settings audio\/display update: High contrast set to on/)).toBeVisible()
  await expect(page.getByText(/Enter a key name or comma-separated alternatives such as B, Space, ArrowUp, or Shift\+L/)).toBeVisible()
  await expect(page.getByLabel('Primary scan')).toHaveValue('Space')
  await expect(page.getByText(/Syngen gamepad input supports left stick or D-pad movement, south button plant\/interact, east button primary scan, west button seed cycling, north button interact\/confirm, shoulder tuning, either trigger plus D-pad/)).toBeVisible()
  await page.getByLabel('Primary scan').fill('b')
  await page.getByLabel('Primary scan').blur()
  await expect(page.getByLabel('Caption and event log').getByText(/Keyboard remap: Primary scan set to b/)).toBeVisible()
  await page.getByRole('button', { name: 'Back to game' }).click()
  await expect(page.locator('.radar')).toBeHidden()
  await expect(page.getByLabel('Caption and event log')).toBeVisible()

  const eventLog = page.getByLabel('Caption and event log')
  await page.getByRole('button', { name: 'Listen' }).click()
  await expect(eventLog.getByText(/Listen: Training Contract: First Breath/)).toBeVisible()
  await page.getByRole('button', { name: 'Locate heart' }).click()
  await expect(eventLog.getByText(/Locate: chamber heart is/)).toBeVisible()
  await expect(eventLog.getByText(/Locate: chamber heart is .* Heart scan: direction .* distance .* objective/)).toBeVisible()
  await page.getByRole('button', { name: 'Tune up' }).click()
  await expect(eventLog.getByText(/Tuned Sol phonoseed: pitchRatio is 1.05/)).toBeVisible()
  await page.getByRole('button', { name: 'Tune down' }).click()
  await expect(eventLog.getByText(/Tuned Sol phonoseed: pitchRatio is 1 .* Single-seed tuning role/)).toBeVisible()
  await page.getByRole('button', { name: 'Restore chamber' }).click()
  await expect(eventLog.getByText(/Restore: Training Contract: First Breath is not ready/)).toBeVisible()
  await page.getByRole('button', { name: 'Evaluate resonance' }).click()
  await expect(eventLog.getByText(/Evaluate resonance: Resonance accuracy 0 percent \(weak\).*Plant 1 more seed/)).toBeVisible()
  await page.keyboard.press('o')
  await expect(eventLog.getByText(/Objective: .* Current system: Intake\./)).toBeVisible()
  await page.keyboard.press('p')
  await expect(eventLog.getByText(/Position: .* facing .* Progress: 0 of \d+ contracts restored; 0 of \d+ Ark systems online/)).toBeVisible()
  await page.keyboard.press('i')
  await expect(eventLog.getByText(/Inventory: Selected seed: Sol phonoseed\. Seed carry limit: \d+ of \d+ carried/)).toBeVisible()
  await page.keyboard.press('l')
  await expect(eventLog.getByText(/Latest log entry: Inventory:/)).toBeVisible()
  await page.keyboard.press('Shift+L')
  await expect(eventLog.getByText(/Recent log: Recent log entries \d+ of \d+: .*Latest log entry: Inventory:/)).toBeVisible()
  await page.keyboard.press('x')
  await expect(eventLog.getByText(/Boundaries for Training Contract: First Breath: west .* Return point .* step\(s\)/)).toBeVisible()
  await expect(eventLog.getByText(/Boundary scan: chamber edges .* Exits: safe return point .* Safe return point/)).toBeVisible()
  await page.keyboard.press('v')
  await expect(eventLog.getByText(/Planted voices: none in this chamber/)).toBeVisible()
  await page.keyboard.press('c')
  await expect(eventLog.getByText(/Codex: no records recovered yet\. Perception updates: Codex recovery:/)).toBeVisible()
  await page.keyboard.press('?')
  await expect(eventLog.getByText(/Controls: move w, ArrowUp\/s, ArrowDown\/a, ArrowLeft\/d, ArrowRight; scan b/)).toBeVisible()
  await expect(eventLog.getByText(/Gamepad: left stick or D-pad moves, south button plants\/interacts, east button scans, west button cycles seeds, north button interacts\/confirms, shoulder buttons tune, hold either trigger plus D-pad/)).toBeVisible()
  await page.keyboard.press('h')
  await expect(page.getByRole('heading', { name: 'Help' })).toBeVisible()
  await expect(page.getByText(/Main campaign chambers never require reflex timing/)).toBeVisible()
  await page.getByRole('button', { name: 'Back to game' }).click()

  await page.keyboard.press('b')
  await expect(eventLog.getByText(/Objective scan: heart/)).toBeVisible()
  await expect(eventLog.getByText(/Objective scan: heart .* Heart scan: direction .* distance .* objective/)).toBeVisible()
  await expect(eventLog.getByText(/shape .* Target traits: .* Hazards: .* Required changes:/)).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('b')
  await expect(eventLog.getByText(/^Boundary scan: chamber edges .* Exits: safe return point .* Safe return point/)).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('b')
  await expect(eventLog.getByText(/Seed scan: no planted seed objects/)).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('b')
  await expect(eventLog.getByText('Hazard scan: no forbidden intervals or unsafe zones detected in this chamber.', { exact: true })).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('b')
  await expect(eventLog.getByText(/^Memory scan: records none recovered yet.*Chamber records: First Breath hidden/)).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('b')
  await expect(eventLog.getByText(/Network scan: endgame multi-chamber resonance building; 0 online system/)).toBeVisible()

  await page.keyboard.press('ArrowUp')
  await expect(eventLog.getByText(/Movement audio: spatial footstep, wall .* current .* landmark heart/)).toBeVisible()
  await expect(eventLog.getByText(/No-sight movement cues: spatial footstep, directional placement, wall distance, exit presence, current status, heart landmark, surface timbre/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Boundary/Objective Scan V1' })).toBeVisible()
  await expect(page.getByText(/Boundary\/objective scan v1 ready: heart bearing, scan range, chamber edges, exits, safe return, and captioned scan actions are available/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'On-Demand Info Commands' })).toBeVisible()
  await expect(page.getByText(/On-demand info commands complete: .*o objective\/current system.*Shift\+L recent log history.*\? controls help/)).toBeVisible()
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await expect(eventLog.getByText(/Meaningful position: within .* chamber heart/)).toBeVisible()
  await page.keyboard.press('v')
  await expect(eventLog.getByText(/Planted voices: Sol phonoseed at .* persistent Sol voice; Tuning state:/)).toBeVisible()
  await expect(eventLog.getByText(/Persistent planted Syngen sound objects active: 1 SeedVoice loop\(s\) for tutorial/)).toBeVisible()
  await page.keyboard.press('z')
  await page.keyboard.press('z')
  await page.keyboard.press('z')
  await page.keyboard.press('b')
  await expect(eventLog.getByText(/Seed scan: Sol phonoseed at .* Tuning state: pitch .* pulse .* brightness .* phase .* waveform/)).toBeVisible()
  await expect(eventLog.getByText(/solved with Resonant rating/)).toBeVisible()
  await expect(eventLog.getByText(/Intake system restored and online/)).toBeVisible()
  await expect(eventLog.getByText(/Seed moves used 1; efficient/)).toBeVisible()
  await expect(eventLog.getByText(/Low-cycle challenge achieved: Training Contract: First Breath/)).toBeVisible()
  await expect(eventLog.getByText(/Graft stability not needed/)).toBeVisible()
  await expect(eventLog.getByText(/Hazard containment clear/)).toBeVisible()
  await expect(eventLog.getByText(/Resource efficiency conserved/)).toBeVisible()
  await expect(eventLog.getByText(/Optional record recovery recovered/)).toBeVisible()
  await page.getByRole('button', { name: 'Restore chamber' }).click()
  await expect(eventLog.getByText(/already restored with Resonant rating/)).toBeVisible()
  await expect(eventLog.getByText(/Codex updated: First Breath/)).toBeVisible()

  await page.getByRole('button', { name: 'Choose next contract' }).click()
  await expect(page.getByRole('heading', { name: 'Restoration Atlas' })).toBeVisible()
  await expect(page.getByText(/Season 1 contracts: 1 restored. Materials: biomass 1/)).toBeVisible()
  await expect(page.getByText(/Atlas status: active work Training Contract: First Breath; next available contract Contract 1: Intake Lung/)).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Restoration atlas actions' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Materials Ledger' })).toBeVisible()
  await expect(page.getByText(/biomass: 1; basic restoration growth and repair work/)).toBeVisible()
  await expect(page.getByText(/spores: 1; common tuning currency/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Resource Dead-End Guard' })).toBeVisible()
  await expect(page.getByText(/Resource dead-end prevention: safe/)).toBeVisible()
  await expect(page.getByText(/Systems online: Intake/)).toBeVisible()
  await expect(page.getByText(/Environmental changes: Intake: Training Contract: First Breath stabilized with Resonant resonance/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Prototype Chamber Slice' })).toBeVisible()
  await expect(page.getByText(/Prototype chamber slice: 10 playable chamber\(s\) in Season 1, plus 1 training contract\(s\); target 8 to 10/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Atlas V1 Checklist' })).toBeVisible()
  await expect(page.getByText(/Restoration atlas v1 ready: work orders, planning, materials, return contracts, codex payoff, and function-menu exits are available/)).toBeVisible()
  await expect(page.getByText(/Functions menu exits: active chamber, seed library, codex perceptions, settings, main menu/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Major Ark Systems' })).toBeVisible()
  await expect(page.getByText(/Heart: network resonance and endgame resolutions/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Stewardship Review' })).toBeVisible()
  await expect(page.locator('section[aria-labelledby="stewardship-title"] p').filter({ hasText: /1 of 4\d contracts restored/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Ark Origin Mystery' })).toBeVisible()
  await expect(page.getByText(/Ark origin mystery: abandoned/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Navigation Atlas' })).toBeVisible()
  await expect(page.getByText(/Navigation atlas previews limited/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Water Root Routing' })).toBeVisible()
  await expect(page.getByText(/Water root routing locked/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Canopy Photosynthesis Doors' })).toBeVisible()
  await expect(page.getByText(/Canopy photosynthesis doors locked/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Memory Codex Echoes' })).toBeVisible()
  await expect(page.getByText(/Memory codex echoes locked/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Heart Network Endings' })).toBeVisible()
  await expect(page.getByText(/Heart network resonance locked/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Final Ecology Philosophy' })).toBeVisible()
  await expect(page.getByText(/Original mission question: return/)).toBeVisible()
  await expect(page.getByText(/Restored ecology question: preserve/)).toBeVisible()
  await expect(page.getByText(/Restoration identity question: living-instrument/)).toBeVisible()
  await expect(page.getByText(/Preservation path: recovering-design/)).toBeVisible()
  await expect(page.getByText(/Adaptation path: dormant/)).toBeVisible()
  await expect(page.getByText(/Conservatory path: cataloguing/)).toBeVisible()
  await expect(page.getByText(/Final ecology philosophy support aligned/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Crew Wake Cycle' })).toBeVisible()
  await expect(page.getByText(/Crew awakening question: not-ready/)).toBeVisible()
  await expect(page.getByText(/Release path: sealed/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Decision Point' })).toBeVisible()
  await expect(page.getByText(/Recommended next work: Contract 1: Intake Lung/)).toBeVisible()
  await expect(page.getByText(/Post-restore options: improve the active chamber, take another work order, research grafts, or advance the Ark clock/)).toBeVisible()
  await page.getByRole('button', { name: 'Advance Ark clock' }).click()
  await expect(page.getByLabel('Caption and event log').getByText(/Ark clock advanced to cycle 1/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Accept work order' }).nth(1)).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Accept work order' }).nth(2)).toBeDisabled()
  await expect(page.getByText(/Teaching axis: chamber heart scan; introduces one new axis/)).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Axis combination mastery: not needed for this single-axis contract/ }).first()).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Optional complexity: expanded optional; may be more complex without blocking the campaign; multi-seed planting, multi-position pattern, harmonic relationship/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Enter active chamber' })).toBeVisible()

  await page.getByRole('button', { name: 'Research grafts' }).click()
  await expect(page.getByRole('heading', { name: 'Seed Library', exact: true })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Seed library actions' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Seed Library Menu' })).toBeVisible()
  await expect(page.getByText(/Seed library menu ready: 6 sections cover collection, tuning, grafting, catalog, preview, and navigation/)).toBeVisible()
  await expect(page.getByText(/Seed library actions: preview selected seed, select seed, tune DNA, lock trait with resin, graft first two seeds, return to atlas, back to chamber/)).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed: Sol phonoseed\. Seed carry limit: \d+ of \d+ carried/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Materials Ledger' })).toBeVisible()
  await expect(page.getByText(/resin: 0; locking seed traits before tuning or grafting/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Grafting Bench', exact: true })).toBeVisible()
  await expect(page.getByText(/Parent A: Sol phonoseed, controls root pitch 1 and waveform sine\. Parent B: Lumen phonoseed/)).toBeVisible()
  await expect(page.getByText(/Bench rule: Parent A passes root pitch and waveform; Parent B passes modulation and growth/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Grafting Bench V1' })).toBeVisible()
  await expect(page.getByText(/Grafting bench v1 ready: two-parent inheritance, material modifiers, useful failures, discovery payoff, and captioned actions are available/)).toBeVisible()
  await expect(page.getByText(/Discovery payoff preview: Sol-Lumen graft; unlocks hybrid resonance planting/)).toBeVisible()
  await expect(page.getByText(/Selected seed DNA: Seed name: Sol phonoseed; catalog id sol/)).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Seed family: Sol; affinity oxygen and stable pitch; discovered origin Intake lung/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Ecological affinity: oxygen and stable pitch; restoration role for Sol ecology/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Discovered origin: Intake lung; origin record for Sol lineage and Memory codex echoes/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Pitch ratio: 1; target delta 0; root interval against the chamber heart/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Pulse rate: 1; target delta 0; rhythmic growth and system timing/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Brightness\/filter: 0.45; target delta 0; filter opening and canopy light color/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Phase: 0 degrees; target offset 0 degrees; alignment, cancellation, and hidden echo behavior/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Waveform: sine; timbre shape for synthesis and graft inheritance; matches any chamber-compatible waveform/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Synth type: (pure|fm|am|noise-kissed); routes to .* Syngen voice/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Modulation profile: FM .*pressure, root grit, and harmonic edge.*AM .*current sway and rhythmic amplitude motion.*noise .*breath, compost, and masking texture.*dominant layer/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Envelope: attack .*how quickly the seed voice blooms.*decay .*sustain .*release .*how long the seed voice lingers.*ADSR shape controls bloom, body, and lingering tail/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Noise profile: .*breath, compost, and masking texture.*routes through .* Syngen/ })).toBeVisible()
  await expect(page.locator('p').filter({ hasText: /Selected seed DNA: .*Growth behavior: .*pulse growth window, about .* seconds; no reflex timing required/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Seed Collection Appraisal' })).toBeVisible()
  await expect(page.getByText(/Exchange remains restoration support/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Seed Family Catalog' })).toBeVisible()
  await expect(page.getByText(/24 known families and 96 possible graft discoveries/)).toBeVisible()
  await page.getByRole('button', { name: 'Select Lumen phonoseed' }).click()
  await expect(page.getByText(/Selected Lumen phonoseed/)).toBeVisible()
  await page.getByRole('button', { name: 'FM modulation' }).click()
  await page.getByRole('button', { name: 'Tune up' }).click()
  await expect(page.getByText(/Tuned Lumen phonoseed: fmAmount is .* FM modulation/)).toBeVisible()
  await page.getByRole('button', { name: 'growth behavior' }).click()
  await page.getByRole('button', { name: 'Tune up' }).click()
  await expect(page.getByText(/Tuned Lumen phonoseed: growthBehavior is .* growth behavior/)).toBeVisible()
  await page.getByRole('button', { name: 'Graft first two seeds' }).click()
  await expect(page.getByText(/First graft: Sol phonoseed plus Lumen phonoseed created Sol-Lumen graft.*root pitch 1 from Sol phonoseed.*waveform sine from Sol phonoseed.*modulation FM .* AM .* noise .* from Lumen phonoseed.*growth .* from Lumen phonoseed/)).toBeVisible()
  await expect(page.getByText(/Grafted Sol-Lumen graft/)).toBeVisible()
  await expect(page.getByText(/Unlocked graft mechanic: hybrid resonance planting/)).toBeVisible()
  await expect(page.locator('li').filter({ hasText: /Sol-Lumen graft: .*Graft ancestry: Sol plus Lumen; archive record sol-lumen; hybrid traits inherited from parent seed lines/ })).toBeVisible()
  await page.getByRole('button', { name: 'Preview selected seed' }).click()
  await expect(page.getByText(/Previewing .* Audio preview: .* waveform .* synth .* growth/)).toBeVisible()
  await page.getByRole('button', { name: 'Atlas' }).click()

  await page.getByRole('button', { name: 'Codex' }).click()
  await expect(page.getByText(/Perception status: \d+ recovered\. Codex recovery:/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Codex Completion' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Codex perception actions' })).toBeVisible()
  await expect(page.getByLabel('Caption and event log')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'First Breath' })).toBeVisible()
})

test('does not request external audio files', async ({ page }) => {
  const requests = []
  page.on('request', (request) => requests.push(request.url()))
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()
  expect(requests.filter((url) => /\.(mp3|wav|ogg|flac|m4a)(\?|$)/i.test(url))).toEqual([])
})

test('supports a no-vision keyboard play path through first restoration', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await expect(page.locator('.a-game--status')).toHaveCount(0)
  await expect(page.locator('.a-game--inventory')).toHaveCount(0)

  await page.keyboard.press('o')
  await expect(eventLog.getByText(/Objective: .* Current system: Intake/)).toBeVisible()
  await page.keyboard.press('p')
  await expect(eventLog.getByText(/Position: .* Progress: 0 of \d+ contracts restored/)).toBeVisible()
  await page.keyboard.press('i')
  await expect(eventLog.getByText(/Inventory: Selected seed: Sol phonoseed/)).toBeVisible()
  await page.keyboard.press('Space')
  await expect(eventLog.getByText(/Objective scan: heart is/)).toBeVisible()
  await page.keyboard.press('ArrowUp')
  await expect(eventLog.getByText(/Movement audio: spatial footstep/)).toBeVisible()
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await expect(eventLog.getByText(/Meaningful position: within .* chamber heart/)).toBeVisible()
  await expect(eventLog.getByText(/Training Contract: First Breath solved with Resonant rating/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Choose next contract' })).toBeVisible()
})

test('supports concise scan verbosity', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('echograft-save-v1', JSON.stringify({
      version: 1,
      currentChamberId: 'tutorial',
      inventoryIds: ['sol', 'lumen', 'umbra'],
      customSeeds: [],
      plantedByChamber: {},
      settings: { scanVerbosity: 'concise' },
    }))
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('Space')
  await expect(eventLog.getByText(/Objective scan: heart .* Required changes:/)).toBeVisible()
  await expect(eventLog.getByText(/Target traits:/)).toHaveCount(0)
})

test('supports optional text-only chamber hints', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('echograft-save-v1', JSON.stringify({
      version: 1,
      currentChamberId: 'tutorial',
      inventoryIds: ['sol', 'lumen', 'umbra'],
      customSeeds: [],
      plantedByChamber: {},
      settings: { textOnlyHints: true },
    }))
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()

  await expect(page.getByRole('heading', { name: 'Text-Only Chamber Hints' })).toBeVisible()
  await expect(page.getByText(/Hint: Plant 1 more seed/)).toBeVisible()
  await expect(page.getByText(/Objective: Move, scan the chamber heart, plant Sol/)).toBeVisible()
})

test('moves with WASD and arrow keys', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('w')
  await expect(eventLog.getByText(/Moved to .* Movement audio: spatial footstep/)).toBeVisible()
  await page.keyboard.press('ArrowDown')
  await expect(eventLog.locator('li').filter({ hasText: /Movement audio: spatial footstep/ })).toHaveCount(2)
})

test('rotates and listens left and right with Q and E', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('q')
  await expect(eventLog.getByText(/Rotated left to 345 degrees\. Listen left: chamber audio is reoriented for left\/right spatial cues\./)).toBeVisible()
  await page.keyboard.press('e')
  await expect(eventLog.getByText(/Rotated right to 0 degrees\. Listen right: chamber audio is reoriented for left\/right spatial cues\./)).toBeVisible()
})

test('uses Space for the primary objective scan', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('Space')
  await expect(eventLog.getByText(/Objective scan: heart is .* Heart scan: direction .* distance .* objective/)).toBeVisible()
})

test('uses Shift+Space for the scan mode menu', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('Shift+Space')
  await expect(eventLog.getByText(/Scan mode menu: boundaries\. Available scan modes: objective, boundaries, seeds, hazards, memory, network\./)).toBeVisible()
  await page.keyboard.press('Space')
  await expect(eventLog.getByText(/Boundary scan: chamber edges/)).toBeVisible()
})

test('uses Enter to plant interact and confirm after solving', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await expect(eventLog.getByText(/Planted Sol phonoseed/)).toBeVisible()
  await expect(eventLog.getByText(/Training Contract: First Breath solved with Resonant rating/)).toBeVisible()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Restoration Atlas' })).toBeVisible()
})

test('uses Tab to cycle the selected seed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('Tab')
  await expect(eventLog.getByText(/Selected Lumen phonoseed\. Selected seed: Lumen phonoseed/)).toBeVisible()
  await page.keyboard.press('Tab')
  await expect(eventLog.getByText(/Selected Umbra phonoseed\. Selected seed: Umbra phonoseed/)).toBeVisible()
})

test('uses Shift+Tab for the previous seed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('Shift+Tab')
  await expect(eventLog.getByText(/Selected Umbra phonoseed\. Selected seed: Umbra phonoseed/)).toBeVisible()
  await page.keyboard.press('Shift+Tab')
  await expect(eventLog.getByText(/Selected Lumen phonoseed\. Selected seed: Lumen phonoseed/)).toBeVisible()
})

test('uses brackets to tune the selected trait', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press(']')
  await expect(eventLog.getByText(/Tuned Sol phonoseed: pitchRatio is 1\.05/)).toBeVisible()
  await page.keyboard.press('[')
  await expect(eventLog.getByText(/Tuned Sol phonoseed: pitchRatio is 1 .* Single-seed tuning role/)).toBeVisible()
})

test('uses number row for seed quick slots and tuning traits', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('2')
  await expect(eventLog.getByText(/Selected Lumen phonoseed\. Selected seed: Lumen phonoseed/)).toBeVisible()
  await page.keyboard.press('Shift+3')
  await expect(eventLog.getByText(/Tuning parameter: brightness\/filter\./)).toBeVisible()
  await page.keyboard.press(']')
  await expect(eventLog.getByText(/Tuned Lumen phonoseed: brightness is 0\.75/)).toBeVisible()
})

test('uses G to graft the first two seeds', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('g')
  await expect(eventLog.getByText(/First graft: Sol phonoseed plus Lumen phonoseed created Sol-Lumen graft/)).toBeVisible()
  await expect(eventLog.getByText(/Grafted Sol-Lumen graft/)).toBeVisible()
  await expect(eventLog.getByText(/Unlocked graft mechanic: hybrid resonance planting/)).toBeVisible()
})

test('uses N to restore or advance when solved', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('n')
  await expect(eventLog.getByText(/Restore: Training Contract: First Breath is not ready/)).toBeVisible()
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await expect(eventLog.getByText(/Training Contract: First Breath solved with Resonant rating/)).toBeVisible()
  await page.keyboard.press('n')
  await expect(eventLog.getByText(/Ark clock advanced to cycle 1/)).toBeVisible()
})

test('always allows chamber reset without punishment', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'New game' }).click()

  const eventLog = page.getByLabel('Caption and event log')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await expect(eventLog.getByText(/Training Contract: First Breath solved with Resonant rating/)).toBeVisible()
  await page.keyboard.press('r')
  await expect(eventLog.getByText(/Chamber reset without punishment: Training Contract: First Breath planted seeds cleared/)).toBeVisible()
  await expect(eventLog.getByText(/Ark clock, materials, ratings, solved contracts, and codex remain unchanged/)).toBeVisible()
  await page.keyboard.press('n')
  await expect(eventLog.getByText(/Ark clock advanced to cycle 1/)).toBeVisible()
})

test('opens the postgame conservatory when unlocked', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('echograft-save-v1', JSON.stringify({
      version: 1,
      currentChamberId: 'finale',
      codexIds: ['first-breath'],
      endgameResolution: 'conservatory',
      materials: { biomass: 3, crystal: 2, memory: 2 },
      plantedByChamber: {},
      postgameUnlocked: true,
      ratings: { finale: 'Resonant' },
      solvedChambers: ['tutorial', 'finale'],
      inventoryIds: ['sol', 'lumen', 'umbra', 'spire'],
      customSeeds: [],
      settings: {},
    }))
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Interact to Begin' }).click()
  await page.getByRole('button', { name: 'Ending resolution' }).click()
  await expect(page.getByText(/Resolution: Conservatory/)).toBeVisible()
  await expect(page.getByText(/Alternate endings: .* selected path conservatory/)).toBeVisible()
  await page.getByRole('button', { name: 'Main menu' }).click()
  await page.getByRole('button', { name: 'Conservatory' }).click()
  await expect(page.getByRole('heading', { name: 'Conservatory' })).toBeVisible()
  await expect(page.getByText(/Postgame restoration is open/)).toBeVisible()
  await expect(page.getByText(/Conservatory path: living-archive/)).toBeVisible()
  await expect(page.getByText(/Composition Palette/)).toBeVisible()
  await expect(page.getByText(/Endless mutation garden ready/)).toBeVisible()
  await page.getByRole('button', { name: 'Grow mutation seed' }).click()
  await expect(page.getByLabel('Caption and event log').getByText(/Endless mutation garden grew Endless Mutation 1/)).toBeVisible()
  await page.getByRole('button', { name: 'Compose conservatory chord' }).click()
  await expect(page.getByText(/Conservatory composition saved: Balanced Chord with 5 voice/)).toBeVisible()
  await expect(page.getByText(/Compose: playing 5 recovered seed voice/)).toBeVisible()
})
