import { createSeedDNA } from './seeds.js'

export function solveTimeText(chamber) {
  const { min, max } = chamber.solveTimeMinutes
  return min === max ? `${min} minute solve` : `${min} to ${max} minute solve`
}

export const campaignScope = {
  firstFullCampaignHours: { min: 6, max: 10 },
  seasons: [
    { id: 1, name: 'Intake and Orientation', requiredContracts: 8, optionalContracts: 2 },
    { id: 2, name: 'Rootworks', requiredContracts: 8, optionalContracts: 4 },
    { id: 3, name: 'Glass Weather', requiredContracts: 8, optionalContracts: 4 },
    { id: 4, name: 'Memory Orchard', requiredContracts: 8, optionalContracts: 4 },
    { id: 5, name: 'Verdancy Heart', requiredContracts: 8, optionalContracts: 4 },
  ],
}

export const chambers = [
  {
    id: 'tutorial',
    title: 'Training Contract: First Breath',
    season: 1,
    system: 'Intake',
    contractType: 'training',
    mechanic: 'movement, listening, and scan',
    objective: 'Move, scan the chamber heart, plant Sol, and match the calm heart tone.',
    start: { x: 0, y: -2, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 5, max: 6 },
    tolerances: { position: 1.5, pitchRatio: 0.15, pulseRate: 0.4, brightness: 0.2, phase: 180 },
    rewards: { codex: ['first-breath'], materials: { biomass: 1 } },
  },
  {
    id: 'direction',
    title: 'Contract 1: Intake Lung',
    season: 1,
    system: 'Intake',
    contractType: 'restoration',
    mechanic: 'movement, listening, and chamber heart scan',
    objective: 'Use repeated scans to find and plant at the chamber heart.',
    start: { x: -3, y: -3, facing: 45 },
    target: { x: 1, y: 1, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 5, max: 7 },
    tolerances: { position: 1.2, pitchRatio: 0.2, pulseRate: 0.5, brightness: 0.25, phase: 180 },
    requires: ['tutorial'],
    rewards: { codex: ['intake-lung'], materials: { biomass: 2 } },
  },
  {
    id: 'binaural',
    title: 'Contract 2: Navigation Grove',
    season: 1,
    system: 'Navigation',
    contractType: 'restoration',
    mechanic: 'direction and distance',
    objective: 'Use scan panning to plant a seed west of the chamber heart.',
    start: { x: 3, y: 0, facing: 270 },
    target: { x: -2, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.2, pitchRatio: 0.2, pulseRate: 0.5, brightness: 0.25, phase: 180 },
    requires: ['direction'],
    rewards: { codex: ['navigation-grove'], materials: { crystal: 1 } },
  },
  {
    id: 'pitch',
    title: 'Contract 3: Water Pump Third',
    season: 1,
    system: 'Water',
    contractType: 'restoration',
    mechanic: 'pitch-ratio matching',
    objective: 'Tune a seed to the bright third: ratio 1.5.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 1, pitchRatio: 1.5, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.5, pitchRatio: 0.08, pulseRate: 0.6, brightness: 0.3, phase: 180 },
    requires: ['binaural'],
    rewards: { codex: ['water-pumps'], materials: { biomass: 1, crystal: 1 } },
  },
  {
    id: 'rhythm',
    title: 'Contract 4: Canopy Pulse Trellis',
    season: 1,
    system: 'Canopy',
    contractType: 'restoration',
    mechanic: 'pulse-rate rhythm matching',
    objective: 'Match the two-beat trellis pulse.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 2, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.5, pitchRatio: 0.25, pulseRate: 0.2, brightness: 0.3, phase: 180 },
    requires: ['pitch'],
    rewards: { codex: ['canopy-pulse'], materials: { biomass: 2 } },
  },
  {
    id: 'timbre',
    title: 'Contract 5: Glass Leaves',
    season: 1,
    system: 'Canopy',
    contractType: 'stabilization',
    mechanic: 'filter brightness',
    objective: 'Raise brightness until the seed cuts through the glass leaves.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.8, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.5, pitchRatio: 0.25, pulseRate: 0.6, brightness: 0.08, phase: 180 },
    requires: ['rhythm'],
    rewards: { codex: ['glass-leaves'], materials: { crystal: 2 } },
  },
  {
    id: 'harmony',
    title: 'Optional Contract: Twin Roots',
    season: 1,
    system: 'Rootworks',
    contractType: 'research',
    mechanic: 'two-seed harmonic planting',
    objective: 'Plant Sol and Lumen together to form a harmonic pair.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1.25, pulseRate: 1.5, brightness: 0.58, phase: 45 },
    requiredSeeds: 2,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 2, pitchRatio: 0.3, pulseRate: 0.6, brightness: 0.25, phase: 180 },
    harmonic: true,
    optional: true,
    requires: ['pitch'],
    rewards: { codex: ['twin-roots'], materials: { memory: 1 } },
  },
  {
    id: 'phase',
    title: 'Contract 6: Quiet Mirror',
    season: 1,
    system: 'Memory',
    contractType: 'restoration',
    mechanic: 'phase and cancellation',
    objective: 'Tune phase near 180 degrees to cancel the mirror drone.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 180 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 1.5, pitchRatio: 0.25, pulseRate: 0.6, brightness: 0.3, phase: 20 },
    requires: ['timbre'],
    rewards: { codex: ['quiet-mirror'], materials: { memory: 2 } },
  },
  {
    id: 'graft',
    title: 'Optional Contract: Splice Nursery',
    season: 1,
    system: 'Research',
    contractType: 'research',
    mechanic: 'grafting',
    objective: 'Graft two seeds and plant the new hybrid near ratio 1.25.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1.25, pulseRate: 1.5, brightness: 0.58, phase: 45 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.5, pitchRatio: 0.15, pulseRate: 0.35, brightness: 0.2, phase: 100 },
    requiresGraft: true,
    optional: true,
    requires: ['harmony'],
    rewards: { codex: ['splice-nursery'], materials: { biomass: 1, memory: 1 } },
  },
  {
    id: 'mold',
    title: 'Contract 7: Mold Pressure Lock',
    season: 1,
    system: 'Intake',
    contractType: 'emergency',
    mechanic: 'hazard intervals',
    objective: 'Avoid the mold interval near 0.75 and tune to 2.0.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 1, y: 0, pitchRatio: 2, pulseRate: 2, brightness: 0.7, phase: 90 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.5, pitchRatio: 0.12, pulseRate: 0.4, brightness: 0.2, phase: 120 },
    hazards: [{ pitchRatio: 0.75, radius: 0.2, message: 'Mold rejects the low fourth interval.' }],
    requires: ['phase'],
    rewards: { codex: ['mold-pressure'], materials: { biomass: 1, memory: 1 }, seeds: ['spire'] },
  },
  {
    id: 'finale',
    title: 'Contract 8: Verdancy Heart',
    season: 1,
    system: 'Heart',
    contractType: 'finale',
    mechanic: 'finale combination',
    objective: 'Use grafting, position, pitch, rhythm, timbre, and phase to restart the Ark.',
    start: { x: 0, y: -4, facing: 0 },
    target: { x: 2, y: 1, pitchRatio: 1.5, pulseRate: 2.5, brightness: 0.75, phase: 90 },
    requiredSeeds: 2,
    solveTimeMinutes: { min: 9, max: 10 },
    tolerances: { position: 1.2, pitchRatio: 0.16, pulseRate: 0.3, brightness: 0.12, phase: 45 },
    harmonic: true,
    requiresGraft: true,
    requires: ['mold'],
    rewards: { codex: ['verdancy-heart'], materials: { biomass: 3, crystal: 2, memory: 2 } },
    ending: true,
  },
]

export const chamberSeeds = {
  sol: createSeedDNA('sol', { name: 'Sol phonoseed', waveform: 'sine', pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 }),
  lumen: createSeedDNA('lumen', { name: 'Lumen phonoseed', waveform: 'triangle', pitchRatio: 1.5, pulseRate: 2, brightness: 0.7, phase: 90 }),
  umbra: createSeedDNA('umbra', { name: 'Umbra phonoseed', waveform: 'square', pitchRatio: 0.75, pulseRate: 0.75, brightness: 0.25, phase: 180 }),
  spire: createSeedDNA('spire', { name: 'Spire phonoseed', waveform: 'sawtooth', pitchRatio: 2, pulseRate: 3, brightness: 0.85, phase: 270 }),
}

export const codexRecords = {
  'first-breath': {
    title: 'First Breath',
    text: 'The Ark still answers small acts of care. A single stable tone can wake a dormant chamber.',
  },
  'intake-lung': {
    title: 'Intake Lung',
    text: 'The intake system once taught seedlings to hear pressure before light. Its pulse is the campaign clock.',
  },
  'navigation-grove': {
    title: 'Navigation Grove',
    text: 'The grove maps space by echo density. Direction is a living trait, not a visual coordinate.',
  },
  'water-pumps': {
    title: 'Water Pumps',
    text: 'Water follows intervals that hold. Bright thirds open valves the old crew could no longer reach.',
  },
  'canopy-pulse': {
    title: 'Canopy Pulse',
    text: 'Canopy lights wake in rhythm. Too much haste makes them flicker; a patient pulse makes them remember.',
  },
  'glass-leaves': {
    title: 'Glass Leaves',
    text: 'Glass-leaf filters bend timbre into heat. Restoring them gives the Ark a warmer listening floor.',
  },
  'twin-roots': {
    title: 'Twin Roots',
    text: 'Two roots can share one harmonic body. This is the first hint that seed families are meant to combine.',
  },
  'quiet-mirror': {
    title: 'Quiet Mirror',
    text: 'The mirror chamber stores absence as data. Phase is memory folded back against itself.',
  },
  'splice-nursery': {
    title: 'Splice Nursery',
    text: 'The nursery did not invent grafting. It listened until two seed voices volunteered a third.',
  },
  'mold-pressure': {
    title: 'Mold Pressure',
    text: 'The mold is not an enemy. It is failed maintenance, singing in intervals the Ark cannot safely digest.',
  },
  'verdancy-heart': {
    title: 'Verdancy Heart',
    text: 'The heart is not a final room. It is a mixer, asking what kind of greenhouse the player has composed.',
  },
}
