import { createSeedDNA } from './seeds.js'

export function solveTimeText(chamber) {
  const { min, max } = chamber.solveTimeMinutes
  return min === max ? `${min} minute solve` : `${min} to ${max} minute solve`
}

export const campaignScope = {
  firstFullCampaignHours: { min: 6, max: 10 },
  seasons: [
    { id: 1, name: 'Intake and Orientation', requiredContracts: 8, optionalContracts: 2 },
    { id: 2, name: 'Rootworks', requiredContracts: 8, optionalContracts: 4 },
    { id: 3, name: 'Glass Weather', requiredContracts: 8, optionalContracts: 4 },
    { id: 4, name: 'Memory Orchard', requiredContracts: 8, optionalContracts: 4 },
    { id: 5, name: 'Verdancy Heart', requiredContracts: 8, optionalContracts: 4 },
  ],
}

export const chambers = [
  {
    id: 'tutorial',
    title: 'Training Contract: First Breath',
    season: 1,
    system: 'Intake',
    contractType: 'training',
    mechanic: 'movement, listening, and scan',
    objective: 'Move, scan the chamber heart, plant Sol, and match the calm heart tone.',
    start: { x: 0, y: -2, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 5, max: 6 },
    tolerances: { position: 1.5, pitchRatio: 0.15, pulseRate: 0.4, brightness: 0.2, phase: 180 },
    rewards: { codex: ['first-breath'], materials: { biomass: 1 } },
  },
  {
    id: 'direction',
    title: 'Contract 1: Intake Lung',
    season: 1,
    system: 'Intake',
    contractType: 'restoration',
    mechanic: 'movement, listening, and chamber heart scan',
    objective: 'Use repeated scans to find and plant at the chamber heart.',
    start: { x: -3, y: -3, facing: 45 },
    target: { x: 1, y: 1, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 5, max: 7 },
    tolerances: { position: 1.2, pitchRatio: 0.2, pulseRate: 0.5, brightness: 0.25, phase: 180 },
    requires: ['tutorial'],
    rewards: { codex: ['intake-lung'], materials: { biomass: 2 } },
  },
  {
    id: 'binaural',
    title: 'Contract 2: Navigation Grove',
    season: 1,
    system: 'Navigation',
    contractType: 'restoration',
    mechanic: 'direction and distance',
    objective: 'Use scan panning to plant a seed west of the chamber heart.',
    start: { x: 3, y: 0, facing: 270 },
    target: { x: -2, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.2, pitchRatio: 0.2, pulseRate: 0.5, brightness: 0.25, phase: 180 },
    requires: ['direction'],
    rewards: { codex: ['navigation-grove'], materials: { crystal: 1 } },
  },
  {
    id: 'pitch',
    title: 'Contract 3: Water Pump Third',
    season: 1,
    system: 'Water',
    contractType: 'restoration',
    mechanic: 'pitch-ratio matching',
    objective: 'Tune a seed to the bright third: ratio 1.5.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 1, pitchRatio: 1.5, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.5, pitchRatio: 0.08, pulseRate: 0.6, brightness: 0.3, phase: 180 },
    requires: ['binaural'],
    rewards: { codex: ['water-pumps'], materials: { biomass: 1, crystal: 1 } },
  },
  {
    id: 'rhythm',
    title: 'Contract 4: Canopy Pulse Trellis',
    season: 1,
    system: 'Canopy',
    contractType: 'restoration',
    mechanic: 'pulse-rate rhythm matching',
    objective: 'Match the two-beat trellis pulse.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 2, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.5, pitchRatio: 0.25, pulseRate: 0.2, brightness: 0.3, phase: 180 },
    requires: ['pitch'],
    rewards: { codex: ['canopy-pulse'], materials: { biomass: 2 } },
  },
  {
    id: 'timbre',
    title: 'Contract 5: Glass Leaves',
    season: 1,
    system: 'Canopy',
    contractType: 'stabilization',
    mechanic: 'filter brightness',
    objective: 'Raise brightness until the seed cuts through the glass leaves.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.8, phase: 0 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.5, pitchRatio: 0.25, pulseRate: 0.6, brightness: 0.08, phase: 180 },
    requires: ['rhythm'],
    rewards: { codex: ['glass-leaves'], materials: { crystal: 2 } },
  },
  {
    id: 'harmony',
    title: 'Optional Contract: Twin Roots',
    season: 1,
    system: 'Rootworks',
    contractType: 'research',
    mechanic: 'two-seed harmonic planting',
    objective: 'Plant Sol and Lumen together to form a harmonic pair.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1.25, pulseRate: 1.5, brightness: 0.58, phase: 45 },
    requiredSeeds: 2,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 2, pitchRatio: 0.3, pulseRate: 0.6, brightness: 0.25, phase: 180 },
    harmonic: true,
    optional: true,
    requires: ['pitch'],
    rewards: { codex: ['twin-roots'], materials: { memory: 1 } },
  },
  {
    id: 'phase',
    title: 'Contract 6: Quiet Mirror',
    season: 1,
    system: 'Memory',
    contractType: 'restoration',
    mechanic: 'phase and cancellation',
    objective: 'Tune phase near 180 degrees to cancel the mirror drone.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 180 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 1.5, pitchRatio: 0.25, pulseRate: 0.6, brightness: 0.3, phase: 20 },
    requires: ['timbre'],
    rewards: { codex: ['quiet-mirror'], materials: { memory: 2 } },
  },
  {
    id: 'graft',
    title: 'Optional Contract: Splice Nursery',
    season: 1,
    system: 'Research',
    contractType: 'research',
    mechanic: 'grafting',
    objective: 'Graft two seeds and plant the new hybrid near ratio 1.25.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1.25, pulseRate: 1.5, brightness: 0.58, phase: 45 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.5, pitchRatio: 0.15, pulseRate: 0.35, brightness: 0.2, phase: 100 },
    requiresGraft: true,
    optional: true,
    requires: ['harmony'],
    rewards: { codex: ['splice-nursery'], materials: { biomass: 1, memory: 1 } },
  },
  {
    id: 'mold',
    title: 'Contract 7: Mold Pressure Lock',
    season: 1,
    system: 'Intake',
    contractType: 'emergency',
    mechanic: 'hazard intervals',
    objective: 'Avoid the mold interval near 0.75 and tune to 2.0.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 1, y: 0, pitchRatio: 2, pulseRate: 2, brightness: 0.7, phase: 90 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.5, pitchRatio: 0.12, pulseRate: 0.4, brightness: 0.2, phase: 120 },
    hazards: [{ pitchRatio: 0.75, radius: 0.2, message: 'Mold rejects the low fourth interval.' }],
    requires: ['phase'],
    rewards: { codex: ['mold-pressure'], materials: { biomass: 1, memory: 1 }, seeds: ['spire'] },
  },
  {
    id: 'finale',
    title: 'Contract 8: Verdancy Heart',
    season: 1,
    system: 'Heart',
    contractType: 'finale',
    mechanic: 'finale combination',
    objective: 'Use grafting, position, pitch, rhythm, timbre, and phase to restart the Ark.',
    start: { x: 0, y: -4, facing: 0 },
    target: { x: 2, y: 1, pitchRatio: 1.5, pulseRate: 2.5, brightness: 0.75, phase: 90 },
    requiredSeeds: 2,
    solveTimeMinutes: { min: 9, max: 10 },
    tolerances: { position: 1.2, pitchRatio: 0.16, pulseRate: 0.3, brightness: 0.12, phase: 45 },
    harmonic: true,
    requiresGraft: true,
    requires: ['mold'],
    rewards: { codex: ['verdancy-heart'], materials: { biomass: 3, crystal: 2, memory: 2 } },
    ending: true,
  },
  {
    id: 'root-reservoir',
    title: 'Contract 9: Root Reservoir',
    season: 2,
    system: 'Rootworks',
    contractType: 'restoration',
    mechanic: 'low-pulse reservoir rooting',
    objective: 'Slow the pulse and plant below the reservoir heart so water can settle into the root mesh.',
    start: { x: -2, y: -4, facing: 0 },
    target: { x: -1, y: 2, pitchRatio: 0.75, pulseRate: 0.75, brightness: 0.35, phase: 45 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.4, pitchRatio: 0.12, pulseRate: 0.18, brightness: 0.16, phase: 50 },
    requires: ['finale'],
    rewards: { materials: { biomass: 2, memory: 1 } },
  },
  {
    id: 'root-choir',
    title: 'Contract 10: Root Choir',
    season: 2,
    system: 'Rootworks',
    contractType: 'restoration',
    mechanic: 'harmonic root pairing',
    objective: 'Plant a paired harmony around the choir node to reconnect split root voices.',
    start: { x: 2, y: -3, facing: 315 },
    target: { x: 1, y: 1, pitchRatio: 1.25, pulseRate: 1.25, brightness: 0.52, phase: 90 },
    requiredSeeds: 2,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 1.8, pitchRatio: 0.2, pulseRate: 0.25, brightness: 0.18, phase: 70 },
    harmonic: true,
    requires: ['root-reservoir'],
    rewards: { materials: { biomass: 2, crystal: 1 } },
  },
  {
    id: 'mycelium-gate',
    title: 'Contract 11: Mycelium Gate',
    season: 2,
    system: 'Rootworks',
    contractType: 'emergency',
    mechanic: 'hazard interval avoidance',
    objective: 'Bypass the sour mold band and tune a bright gate tone for safe fungal traffic.',
    start: { x: -4, y: -1, facing: 90 },
    target: { x: 2, y: -1, pitchRatio: 1.5, pulseRate: 1.75, brightness: 0.68, phase: 120 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.3, pitchRatio: 0.1, pulseRate: 0.3, brightness: 0.14, phase: 55 },
    hazards: [{ pitchRatio: 0.67, radius: 0.18, message: 'Mycelium gate buckles around the sour mold band.' }],
    requires: ['root-choir'],
    rewards: { materials: { biomass: 1, memory: 2 } },
  },
  {
    id: 'optional-root-echo',
    title: 'Optional Contract: Root Echo Survey',
    season: 2,
    system: 'Rootworks',
    contractType: 'survey',
    mechanic: 'phase echo mapping',
    objective: 'Map a delayed root echo by tuning phase before the next mainline gate opens.',
    start: { x: 0, y: -4, facing: 0 },
    target: { x: -2, y: 1, pitchRatio: 1, pulseRate: 1.5, brightness: 0.42, phase: 210 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.6, pitchRatio: 0.2, pulseRate: 0.35, brightness: 0.22, phase: 25 },
    optional: true,
    requires: ['root-choir'],
    rewards: { materials: { memory: 2 } },
  },
  {
    id: 'pressure-orchard',
    title: 'Contract 12: Pressure Orchard',
    season: 2,
    system: 'Intake',
    contractType: 'stabilization',
    mechanic: 'pressure rhythm balancing',
    objective: 'Balance intake pressure with a steady two-and-a-half pulse under the orchard vents.',
    start: { x: 3, y: -3, facing: 300 },
    target: { x: 0, y: 2, pitchRatio: 1, pulseRate: 2.5, brightness: 0.58, phase: 60 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 1.5, pitchRatio: 0.18, pulseRate: 0.22, brightness: 0.16, phase: 65 },
    requires: ['mycelium-gate'],
    rewards: { materials: { biomass: 2, crystal: 1 } },
  },
  {
    id: 'optional-rhizome-splice',
    title: 'Optional Contract: Rhizome Splice',
    season: 2,
    system: 'Research',
    contractType: 'research',
    mechanic: 'grafted root behavior',
    objective: 'Use a grafted seed to teach a split rhizome to carry two growth behaviors at once.',
    start: { x: -3, y: -2, facing: 45 },
    target: { x: 1, y: 0, pitchRatio: 1.25, pulseRate: 1.75, brightness: 0.62, phase: 135 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.5, pitchRatio: 0.16, pulseRate: 0.28, brightness: 0.18, phase: 60 },
    requiresGraft: true,
    optional: true,
    requires: ['optional-root-echo'],
    rewards: { materials: { biomass: 1, memory: 2 } },
  },
  {
    id: 'nutrient-lattice',
    title: 'Contract 13: Nutrient Lattice',
    season: 2,
    system: 'Water',
    contractType: 'restoration',
    mechanic: 'bright lattice tuning',
    objective: 'Raise the lattice brightness without pushing the nutrient line into overload.',
    start: { x: 0, y: -4, facing: 0 },
    target: { x: -1, y: -1, pitchRatio: 1.5, pulseRate: 2, brightness: 0.78, phase: 45 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 1.3, pitchRatio: 0.12, pulseRate: 0.25, brightness: 0.1, phase: 55 },
    requires: ['pressure-orchard'],
    rewards: { materials: { crystal: 2, memory: 1 } },
  },
  {
    id: 'optional-deep-root',
    title: 'Optional Contract: Deep Root Solo',
    season: 2,
    system: 'Rootworks',
    contractType: 'challenge',
    mechanic: 'single-seed precision',
    objective: 'Restore a deep root with one seed and a narrow phase window.',
    start: { x: 2, y: -4, facing: 330 },
    target: { x: 2, y: 2, pitchRatio: 0.75, pulseRate: 1, brightness: 0.3, phase: 270 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.1, pitchRatio: 0.08, pulseRate: 0.22, brightness: 0.14, phase: 22 },
    optional: true,
    requires: ['nutrient-lattice'],
    rewards: { materials: { biomass: 2, memory: 1 } },
  },
  {
    id: 'glass-rain',
    title: 'Contract 14: Glass Rain',
    season: 3,
    system: 'Glass Weather',
    contractType: 'restoration',
    mechanic: 'rain pulse shaping',
    objective: 'Shape a gentle rain pulse that wets the glass canopy without cracking it.',
    start: { x: -2, y: -3, facing: 20 },
    target: { x: 0, y: 1, pitchRatio: 1, pulseRate: 1.75, brightness: 0.66, phase: 30 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.5, pitchRatio: 0.16, pulseRate: 0.22, brightness: 0.12, phase: 50 },
    requires: ['nutrient-lattice'],
    rewards: { materials: { crystal: 2 } },
  },
  {
    id: 'sun-prism',
    title: 'Contract 15: Sun Prism',
    season: 3,
    system: 'Glass Weather',
    contractType: 'stabilization',
    mechanic: 'high-brightness prism focus',
    objective: 'Focus a high-brightness tone into the prism so the Ark can read sunlight again.',
    start: { x: 3, y: -2, facing: 290 },
    target: { x: 1, y: 2, pitchRatio: 2, pulseRate: 1.5, brightness: 0.85, phase: 90 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 1.4, pitchRatio: 0.14, pulseRate: 0.28, brightness: 0.08, phase: 50 },
    requires: ['glass-rain'],
    rewards: { materials: { crystal: 2, biomass: 1 } },
  },
  {
    id: 'fog-harp',
    title: 'Contract 16: Fog Harp',
    season: 3,
    system: 'Glass Weather',
    contractType: 'restoration',
    mechanic: 'noise-bed thinning',
    objective: 'Thin the fog harp with a clear tone that keeps noise below the chamber heart.',
    start: { x: -4, y: 0, facing: 90 },
    target: { x: 2, y: 0, pitchRatio: 1.25, pulseRate: 1.25, brightness: 0.5, phase: 180 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 1.5, pitchRatio: 0.16, pulseRate: 0.25, brightness: 0.18, phase: 40 },
    requires: ['sun-prism'],
    rewards: { materials: { memory: 1, crystal: 1 } },
  },
  {
    id: 'optional-rain-return',
    title: 'Optional Contract: Rain Return',
    season: 3,
    system: 'Glass Weather',
    contractType: 'challenge',
    mechanic: 'off-axis weather planting',
    objective: 'Restore a rain return node from an off-axis position using distance scans only.',
    start: { x: 4, y: -4, facing: 315 },
    target: { x: -2, y: 2, pitchRatio: 1, pulseRate: 2.25, brightness: 0.6, phase: 75 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.2, pitchRatio: 0.14, pulseRate: 0.2, brightness: 0.16, phase: 55 },
    optional: true,
    requires: ['glass-rain'],
    rewards: { materials: { crystal: 1, memory: 1 } },
  },
  {
    id: 'hail-damper',
    title: 'Contract 17: Hail Damper',
    season: 3,
    system: 'Glass Weather',
    contractType: 'emergency',
    mechanic: 'phase damper',
    objective: 'Tune a damper phase that turns hail clicks into a slow maintenance pulse.',
    start: { x: 0, y: -4, facing: 0 },
    target: { x: 0, y: 2, pitchRatio: 0.75, pulseRate: 0.75, brightness: 0.48, phase: 225 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.4, pitchRatio: 0.1, pulseRate: 0.16, brightness: 0.18, phase: 28 },
    hazards: [{ pulseRate: 3, radius: 0.25, message: 'Hail surge rejects frantic pulses.' }],
    requires: ['fog-harp'],
    rewards: { materials: { crystal: 2, memory: 1 } },
  },
  {
    id: 'optional-prism-duet',
    title: 'Optional Contract: Prism Duet',
    season: 3,
    system: 'Glass Weather',
    contractType: 'research',
    mechanic: 'two-seed prism harmony',
    objective: 'Plant two bright voices around the prism to recover a lost weather overtone.',
    start: { x: -3, y: -3, facing: 45 },
    target: { x: 1, y: -1, pitchRatio: 1.5, pulseRate: 2, brightness: 0.82, phase: 120 },
    requiredSeeds: 2,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.8, pitchRatio: 0.2, pulseRate: 0.32, brightness: 0.12, phase: 70 },
    harmonic: true,
    optional: true,
    requires: ['sun-prism'],
    rewards: { materials: { crystal: 2 } },
  },
  {
    id: 'wind-bellows',
    title: 'Contract 18: Wind Bellows',
    season: 3,
    system: 'Intake',
    contractType: 'restoration',
    mechanic: 'airflow pulse routing',
    objective: 'Route wind through the bellows with a stable pulse and moderate brightness.',
    start: { x: 2, y: -4, facing: 340 },
    target: { x: -1, y: 1, pitchRatio: 1.25, pulseRate: 2, brightness: 0.55, phase: 60 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.5, pitchRatio: 0.16, pulseRate: 0.22, brightness: 0.16, phase: 55 },
    requires: ['hail-damper'],
    rewards: { materials: { biomass: 1, crystal: 1 } },
  },
  {
    id: 'optional-fog-braid',
    title: 'Optional Contract: Fog Braid',
    season: 3,
    system: 'Research',
    contractType: 'challenge',
    mechanic: 'grafted fog behavior',
    objective: 'Use a grafted seed to braid fog and wind into one navigable corridor.',
    start: { x: -1, y: -4, facing: 0 },
    target: { x: 2, y: 1, pitchRatio: 1.25, pulseRate: 1.75, brightness: 0.58, phase: 150 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.4, pitchRatio: 0.14, pulseRate: 0.24, brightness: 0.14, phase: 45 },
    requiresGraft: true,
    optional: true,
    requires: ['fog-harp'],
    rewards: { materials: { memory: 2 } },
  },
  {
    id: 'memory-pond',
    title: 'Contract 19: Memory Pond',
    season: 4,
    system: 'Memory Orchard',
    contractType: 'restoration',
    mechanic: 'soft phase recall',
    objective: 'Wake the memory pond with a soft phase offset that does not erase old reflections.',
    start: { x: 0, y: -4, facing: 0 },
    target: { x: -1, y: 2, pitchRatio: 1, pulseRate: 1, brightness: 0.4, phase: 135 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 6, max: 8 },
    tolerances: { position: 1.5, pitchRatio: 0.18, pulseRate: 0.28, brightness: 0.2, phase: 35 },
    requires: ['wind-bellows'],
    rewards: { materials: { memory: 2 } },
  },
  {
    id: 'archive-vines',
    title: 'Contract 20: Archive Vines',
    season: 4,
    system: 'Memory Orchard',
    contractType: 'restoration',
    mechanic: 'braided archive rhythm',
    objective: 'Thread archive vines through a slow rhythm so recovered records stay attached.',
    start: { x: -3, y: -3, facing: 45 },
    target: { x: 1, y: 1, pitchRatio: 1.25, pulseRate: 1.5, brightness: 0.48, phase: 180 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 1.4, pitchRatio: 0.14, pulseRate: 0.24, brightness: 0.16, phase: 38 },
    requires: ['memory-pond'],
    rewards: { materials: { biomass: 1, memory: 2 } },
  },
  {
    id: 'optional-record-grove',
    title: 'Optional Contract: Record Grove',
    season: 4,
    system: 'Memory Orchard',
    contractType: 'survey',
    mechanic: 'record recovery scan',
    objective: 'Recover a quiet record grove by matching a fragile high-phase memory tone.',
    start: { x: 3, y: -4, facing: 320 },
    target: { x: -2, y: 0, pitchRatio: 1.5, pulseRate: 1, brightness: 0.5, phase: 255 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 1.2, pitchRatio: 0.1, pulseRate: 0.22, brightness: 0.16, phase: 25 },
    optional: true,
    requires: ['memory-pond'],
    rewards: { materials: { memory: 2 } },
  },
  {
    id: 'ancestor-filter',
    title: 'Contract 21: Ancestor Filter',
    season: 4,
    system: 'Memory Orchard',
    contractType: 'stabilization',
    mechanic: 'timbre memory filtering',
    objective: 'Brighten the ancestor filter enough to separate useful memory from static.',
    start: { x: -4, y: 1, facing: 90 },
    target: { x: 2, y: -1, pitchRatio: 1, pulseRate: 2, brightness: 0.76, phase: 90 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 1.4, pitchRatio: 0.14, pulseRate: 0.24, brightness: 0.08, phase: 45 },
    requires: ['archive-vines'],
    rewards: { materials: { crystal: 1, memory: 2 } },
  },
  {
    id: 'optional-whisper-formant',
    title: 'Optional Contract: Whisper Formant',
    season: 4,
    system: 'Research',
    contractType: 'research',
    mechanic: 'formant-like graft study',
    objective: 'Use a grafted voice to shape a whisper formant for later seed research.',
    start: { x: 2, y: -3, facing: 315 },
    target: { x: 0, y: 1, pitchRatio: 1.25, pulseRate: 1.25, brightness: 0.64, phase: 210 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.5, pitchRatio: 0.14, pulseRate: 0.24, brightness: 0.14, phase: 45 },
    requiresGraft: true,
    optional: true,
    requires: ['optional-record-grove'],
    rewards: { materials: { memory: 3 } },
  },
  {
    id: 'dream-compost',
    title: 'Contract 22: Dream Compost',
    season: 4,
    system: 'Rootworks',
    contractType: 'restoration',
    mechanic: 'low-memory composting',
    objective: 'Compost corrupted memories with a low interval and a patient pulse.',
    start: { x: 0, y: -4, facing: 0 },
    target: { x: 1, y: 2, pitchRatio: 0.75, pulseRate: 0.75, brightness: 0.38, phase: 180 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.5, pitchRatio: 0.1, pulseRate: 0.16, brightness: 0.18, phase: 32 },
    requires: ['ancestor-filter'],
    rewards: { materials: { biomass: 2, memory: 1 } },
  },
  {
    id: 'optional-pastoral-loop',
    title: 'Optional Contract: Pastoral Loop',
    season: 4,
    system: 'Memory Orchard',
    contractType: 'challenge',
    mechanic: 'looped melody planting',
    objective: 'Tune a pastoral loop that can be replayed later in the Conservatory.',
    start: { x: -2, y: -4, facing: 30 },
    target: { x: 2, y: 2, pitchRatio: 1.5, pulseRate: 2.25, brightness: 0.58, phase: 105 },
    requiredSeeds: 2,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.8, pitchRatio: 0.18, pulseRate: 0.24, brightness: 0.16, phase: 65 },
    harmonic: true,
    optional: true,
    requires: ['archive-vines'],
    rewards: { materials: { memory: 2 } },
  },
  {
    id: 'orchard-gate',
    title: 'Contract 23: Orchard Gate',
    season: 4,
    system: 'Memory Orchard',
    contractType: 'restoration',
    mechanic: 'gate phase alignment',
    objective: 'Open the orchard gate by lining memory phase with a bright navigation tone.',
    start: { x: 4, y: -3, facing: 300 },
    target: { x: -1, y: 1, pitchRatio: 1.5, pulseRate: 1.75, brightness: 0.7, phase: 180 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 7, max: 9 },
    tolerances: { position: 1.3, pitchRatio: 0.12, pulseRate: 0.22, brightness: 0.12, phase: 34 },
    requires: ['dream-compost'],
    rewards: { materials: { crystal: 1, memory: 2 } },
  },
  {
    id: 'optional-mirror-return',
    title: 'Optional Contract: Mirror Return',
    season: 4,
    system: 'Memory Orchard',
    contractType: 'challenge',
    mechanic: 'narrow phase cancellation',
    objective: 'Return to the mirror technique with a stricter cancellation window.',
    start: { x: -4, y: -2, facing: 70 },
    target: { x: 1, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.44, phase: 180 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.1, pitchRatio: 0.08, pulseRate: 0.18, brightness: 0.12, phase: 18 },
    optional: true,
    requires: ['ancestor-filter'],
    rewards: { materials: { memory: 2 } },
  },
  {
    id: 'heart-atria',
    title: 'Contract 24: Heart Atria',
    season: 5,
    system: 'Verdancy Heart',
    contractType: 'restoration',
    mechanic: 'heart rhythm priming',
    objective: 'Prime the Ark heart atria with a strong but steady restoration pulse.',
    start: { x: 0, y: -4, facing: 0 },
    target: { x: 0, y: 1, pitchRatio: 1.25, pulseRate: 2.5, brightness: 0.7, phase: 90 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.4, pitchRatio: 0.14, pulseRate: 0.22, brightness: 0.12, phase: 45 },
    requires: ['orchard-gate'],
    rewards: { materials: { biomass: 2, crystal: 1, memory: 1 } },
  },
  {
    id: 'optional-heart-glass',
    title: 'Optional Contract: Heart Glass',
    season: 5,
    system: 'Verdancy Heart',
    contractType: 'challenge',
    mechanic: 'bright finale preparation',
    objective: 'Polish the heart glass with a high-brightness tone before choosing an ending posture.',
    start: { x: 3, y: -4, facing: 320 },
    target: { x: -1, y: 2, pitchRatio: 2, pulseRate: 2, brightness: 0.86, phase: 120 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.2, pitchRatio: 0.1, pulseRate: 0.18, brightness: 0.08, phase: 36 },
    optional: true,
    requires: ['heart-atria'],
    rewards: { materials: { crystal: 2, memory: 1 } },
  },
  {
    id: 'optional-heart-root',
    title: 'Optional Contract: Heart Root',
    season: 5,
    system: 'Verdancy Heart',
    contractType: 'challenge',
    mechanic: 'deep finale preparation',
    objective: 'Anchor the heart roots with a low interval that favors slow ecological recovery.',
    start: { x: -3, y: -4, facing: 40 },
    target: { x: 2, y: 1, pitchRatio: 0.75, pulseRate: 0.75, brightness: 0.36, phase: 210 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.3, pitchRatio: 0.1, pulseRate: 0.16, brightness: 0.14, phase: 34 },
    optional: true,
    requires: ['heart-atria'],
    rewards: { materials: { biomass: 2, memory: 1 } },
  },
  {
    id: 'optional-heart-memory',
    title: 'Optional Contract: Heart Memory',
    season: 5,
    system: 'Verdancy Heart',
    contractType: 'challenge',
    mechanic: 'memory finale preparation',
    objective: 'Carry recovered memory into the heart with a precise phase braid.',
    start: { x: 0, y: -4, facing: 0 },
    target: { x: 1, y: 2, pitchRatio: 1.5, pulseRate: 1.5, brightness: 0.62, phase: 240 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 8, max: 10 },
    tolerances: { position: 1.3, pitchRatio: 0.12, pulseRate: 0.2, brightness: 0.12, phase: 30 },
    optional: true,
    requires: ['heart-atria'],
    rewards: { materials: { memory: 3 } },
  },
  {
    id: 'optional-heart-graft',
    title: 'Optional Contract: Heart Graft',
    season: 5,
    system: 'Verdancy Heart',
    contractType: 'research',
    mechanic: 'grafted ending preparation',
    objective: 'Use a grafted voice to prepare a hybrid ending path for the Verdancy Heart.',
    start: { x: -2, y: -4, facing: 25 },
    target: { x: 2, y: 2, pitchRatio: 1.25, pulseRate: 2.25, brightness: 0.72, phase: 150 },
    requiredSeeds: 1,
    solveTimeMinutes: { min: 9, max: 10 },
    tolerances: { position: 1.3, pitchRatio: 0.12, pulseRate: 0.2, brightness: 0.12, phase: 38 },
    requiresGraft: true,
    optional: true,
    requires: ['heart-atria'],
    rewards: { materials: { biomass: 1, crystal: 1, memory: 2 } },
  },
]

export const chamberSeeds = {
  sol: createSeedDNA('sol', { name: 'Sol phonoseed', waveform: 'sine', pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 }),
  lumen: createSeedDNA('lumen', { name: 'Lumen phonoseed', waveform: 'triangle', pitchRatio: 1.5, pulseRate: 2, brightness: 0.7, phase: 90 }),
  umbra: createSeedDNA('umbra', { name: 'Umbra phonoseed', waveform: 'square', pitchRatio: 0.75, pulseRate: 0.75, brightness: 0.25, phase: 180 }),
  spire: createSeedDNA('spire', { name: 'Spire phonoseed', waveform: 'sawtooth', pitchRatio: 2, pulseRate: 3, brightness: 0.85, phase: 270 }),
}

export const codexRecords = {
  'first-breath': {
    title: 'First Breath',
    text: 'The Ark still answers small acts of care. A single stable tone can wake a dormant chamber.',
  },
  'intake-lung': {
    title: 'Intake Lung',
    text: 'The intake system once taught seedlings to hear pressure before light. Its pulse is the campaign clock.',
  },
  'navigation-grove': {
    title: 'Navigation Grove',
    text: 'The grove maps space by echo density. Direction is a living trait, not a visual coordinate.',
  },
  'water-pumps': {
    title: 'Water Pumps',
    text: 'Water follows intervals that hold. Bright thirds open valves the old crew could no longer reach.',
  },
  'canopy-pulse': {
    title: 'Canopy Pulse',
    text: 'Canopy lights wake in rhythm. Too much haste makes them flicker; a patient pulse makes them remember.',
  },
  'glass-leaves': {
    title: 'Glass Leaves',
    text: 'Glass-leaf filters bend timbre into heat. Restoring them gives the Ark a warmer listening floor.',
  },
  'twin-roots': {
    title: 'Twin Roots',
    text: 'Two roots can share one harmonic body. This is the first hint that seed families are meant to combine.',
  },
  'quiet-mirror': {
    title: 'Quiet Mirror',
    text: 'The mirror chamber stores absence as data. Phase is memory folded back against itself.',
  },
  'splice-nursery': {
    title: 'Splice Nursery',
    text: 'The nursery did not invent grafting. It listened until two seed voices volunteered a third.',
  },
  'mold-pressure': {
    title: 'Mold Pressure',
    text: 'The mold is not an enemy. It is failed maintenance, singing in intervals the Ark cannot safely digest.',
  },
  'verdancy-heart': {
    title: 'Verdancy Heart',
    text: 'The heart is not a final room. It is a mixer, asking what kind of greenhouse the player has composed.',
  },
}
