import { createSeedDNA } from './seeds.js'

export const chambers = [
  {
    id: 'tutorial',
    title: 'Tutorial: First Breath',
    mechanic: 'movement, listening, and scan',
    objective: 'Move, scan the chamber heart, plant Sol, and match the calm heart tone.',
    start: { x: 0, y: -2, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    tolerances: { position: 1.5, pitchRatio: 0.15, pulseRate: 0.4, brightness: 0.2, phase: 180 },
    grants: ['sol'],
  },
  {
    id: 'direction',
    title: 'Chamber 1: Heart Echo',
    mechanic: 'movement, listening, and chamber heart scan',
    objective: 'Use repeated scans to find and plant at the chamber heart.',
    start: { x: -3, y: -3, facing: 45 },
    target: { x: 1, y: 1, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    tolerances: { position: 1.2, pitchRatio: 0.2, pulseRate: 0.5, brightness: 0.25, phase: 180 },
  },
  {
    id: 'binaural',
    title: 'Chamber 2: Left of the Heart',
    mechanic: 'direction and distance',
    objective: 'Use scan panning to plant a seed west of the chamber heart.',
    start: { x: 3, y: 0, facing: 270 },
    target: { x: -2, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    tolerances: { position: 1.2, pitchRatio: 0.2, pulseRate: 0.5, brightness: 0.25, phase: 180 },
  },
  {
    id: 'pitch',
    title: 'Chamber 3: Third Bloom',
    mechanic: 'pitch-ratio matching',
    objective: 'Tune a seed to the bright third: ratio 1.5.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 1, pitchRatio: 1.5, pulseRate: 1, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    tolerances: { position: 1.5, pitchRatio: 0.08, pulseRate: 0.6, brightness: 0.3, phase: 180 },
  },
  {
    id: 'rhythm',
    title: 'Chamber 4: Pulse Trellis',
    mechanic: 'pulse-rate rhythm matching',
    objective: 'Match the two-beat trellis pulse.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 2, brightness: 0.45, phase: 0 },
    requiredSeeds: 1,
    tolerances: { position: 1.5, pitchRatio: 0.25, pulseRate: 0.2, brightness: 0.3, phase: 180 },
  },
  {
    id: 'timbre',
    title: 'Chamber 5: Glass Leaves',
    mechanic: 'filter brightness',
    objective: 'Raise brightness until the seed cuts through the glass leaves.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.8, phase: 0 },
    requiredSeeds: 1,
    tolerances: { position: 1.5, pitchRatio: 0.25, pulseRate: 0.6, brightness: 0.08, phase: 180 },
  },
  {
    id: 'harmony',
    title: 'Chamber 6: Twin Roots',
    mechanic: 'two-seed harmonic planting',
    objective: 'Plant Sol and Lumen together to form a harmonic pair.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1.25, pulseRate: 1.5, brightness: 0.58, phase: 45 },
    requiredSeeds: 2,
    tolerances: { position: 2, pitchRatio: 0.3, pulseRate: 0.6, brightness: 0.25, phase: 180 },
    harmonic: true,
  },
  {
    id: 'phase',
    title: 'Chamber 7: Quiet Mirror',
    mechanic: 'phase and cancellation',
    objective: 'Tune phase near 180 degrees to cancel the mirror drone.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 180 },
    requiredSeeds: 1,
    tolerances: { position: 1.5, pitchRatio: 0.25, pulseRate: 0.6, brightness: 0.3, phase: 20 },
  },
  {
    id: 'graft',
    title: 'Chamber 8: Splice Nursery',
    mechanic: 'grafting',
    objective: 'Graft two seeds and plant the new hybrid near ratio 1.25.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 0, y: 0, pitchRatio: 1.25, pulseRate: 1.5, brightness: 0.58, phase: 45 },
    requiredSeeds: 1,
    tolerances: { position: 1.5, pitchRatio: 0.15, pulseRate: 0.35, brightness: 0.2, phase: 100 },
    requiresGraft: true,
  },
  {
    id: 'mold',
    title: 'Chamber 9: Hostile Mold',
    mechanic: 'hazard intervals',
    objective: 'Avoid the mold interval near 0.75 and tune to 2.0.',
    start: { x: 0, y: -3, facing: 0 },
    target: { x: 1, y: 0, pitchRatio: 2, pulseRate: 2, brightness: 0.7, phase: 90 },
    requiredSeeds: 1,
    tolerances: { position: 1.5, pitchRatio: 0.12, pulseRate: 0.4, brightness: 0.2, phase: 120 },
    hazards: [{ pitchRatio: 0.75, radius: 0.2, message: 'Mold rejects the low fourth interval.' }],
    grants: ['spire'],
  },
  {
    id: 'finale',
    title: 'Chamber 10: Verdancy Heart',
    mechanic: 'finale combination',
    objective: 'Use grafting, position, pitch, rhythm, timbre, and phase to restart the Ark.',
    start: { x: 0, y: -4, facing: 0 },
    target: { x: 2, y: 1, pitchRatio: 1.5, pulseRate: 2.5, brightness: 0.75, phase: 90 },
    requiredSeeds: 2,
    tolerances: { position: 1.2, pitchRatio: 0.16, pulseRate: 0.3, brightness: 0.12, phase: 45 },
    harmonic: true,
    requiresGraft: true,
    ending: true,
  },
]

export const chamberSeeds = {
  sol: createSeedDNA('sol', { name: 'Sol phonoseed', waveform: 'sine', pitchRatio: 1, pulseRate: 1, brightness: 0.45, phase: 0 }),
  lumen: createSeedDNA('lumen', { name: 'Lumen phonoseed', waveform: 'triangle', pitchRatio: 1.5, pulseRate: 2, brightness: 0.7, phase: 90 }),
  umbra: createSeedDNA('umbra', { name: 'Umbra phonoseed', waveform: 'square', pitchRatio: 0.75, pulseRate: 0.75, brightness: 0.25, phase: 180 }),
  spire: createSeedDNA('spire', { name: 'Spire phonoseed', waveform: 'sawtooth', pitchRatio: 2, pulseRate: 3, brightness: 0.85, phase: 270 }),
}
